name: checkit
description: A fast, modular validation library for Dart and Flutter projects.
version: 1.0.0
repository: https://github.com/4e6anenk0/checkit
homepage: https://github.com/4e6anenk0/checkit
issue_tracker: https://github.com/4e6anenk0/checkit/issues
topics: [validation, validator, checking]

environment:
  sdk: '>=3.0.0 <4.0.0'

# Add regular dependencies here.
#dependencies:

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  validart: ^0.1.2
  formz: ^0.8.0
  benchmark_harness: ^2.3.1

screenshots:
  - description: The checkit package logo.
    path: assets/logo-big.png
